name: AUTO

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.1

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.6

      - name: Run Test
        run: gradle test
