name: AUTO

on: [push]

permissions:
  actions: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check changes
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            math: 'math_util/**'

      - name: Setup Java 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Run Test
        run: |
            if [ ${{ steps.changes.outputs.math == 'false' }} ]; then
              gradle :profiling_util:test
            else
              gradle test
            fi

      - name: Filter Formating Files
        uses: dorny/paths-filter@v3.0.1
        id: files
        with:
          list-files: shell
          filters: |
            src:
              - added|modified: 'math_util/**/*.cpp'
              - added|modified: 'math_util/**/*.hpp'
              - added|modified: 'profiling_util/**/*.cpp'
              - added|modified: 'profiling_util/**/*.hpp'

      - name: Formating File
        run: |
          echo ${{ steps.files.outputs.src_files }}
          sudo apt-get install -y clang-format
          find . -iname "*.cpp" -o -iname "*.hpp" | xargs clang-format -i

      - name: Publish in github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

