name: AUTO

on:
  push:
    paths:
      - 'math_util/**'
      - 'profiling_util/**'

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4.1.1

      - uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            math:
              - 'math_util/**'
            profiling:
              - 'profiling_util/**'

      - uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Run Math Utility Test
        if: steps.changes.outputs.math == 'true'
        run: gradle :math_util:test

      - name: Run Profiling Utility Test
        if: steps.changes.outputs.profiling == 'true'
        run: gradle :profiling_util:test
