name: AUTO

on: [push]

permissions:
  actions: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Check changes
        uses: dorny/paths-filter@v3.0.1
        id: changes
        with:
          filters: |
            math: 'math_util/**'

      - name: Setup Java 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Run Test
        run: |
            if [ ${{ steps.changes.outputs.math == 'false' }} ]; then
              gradle :profiling_util:test
            else
              gradle test
            fi

      - name: Filter Formating Files
        uses: dorny/paths-filter@v3.0.1
        id: files
        with:
          list-files: shell
          filters: |
            src:
              - 'math_util/**/*.cpp'
              - 'math_util/**/*.hpp'
              - 'profiling_util/**/*.cpp'
              - 'profiling_util/**/*.hpp'

      - name: Formating File
        run: |
          sudo apt-get install -y clang-format
          clang-format -i ${{ steps.files.output.src_files }}

      - name: Commit and Push format
        run: |
          git config --global user.email "ikomangwidiadaariasa12@gmail.com"
          git config --global user.name "AriasaProp"
          git add .
          git commit -m "Reformatting cpp"
          git push
