name: Clean Workflows

on: [workflow_dispatch]

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Delete workflow runs
        run: |
          while OT=$(gh api repos/AriasaProp/Function_Test/actions/runs --jq '.workflow_runs[] | .id'); [ -n "$OT" ]; do
            for run_id in $OT; do
              gh api repos/AriasaProp/Function_Test/actions/runs/$run_id --method DELETE;
            done;
          done;
          
