name: Code Formatter

on: [workflow_dispatch]

jobs:
  clang-format:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: AutoModality/action-ros-clang-format@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}