name: Formating Code

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Safe
        run: 	git config --global --add safe.directory ${{ github.workspace }}
      - uses: AutoModality/action-ros-clang-format@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
