name: Rebuild and Push Gradle Project

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.2
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Gradle Test
      uses: gradle/gradle-build-action@v2.4.2
      with:
        gradle-version: 8.6
        arguments: rebuild
    - name: Commit and push changes
      run: |
        git config --global user.email "ikomangwidiadaariasa12@gmail.com"
        git config --global user.name "AriasaProp"
        git add .
        git commit -m "rebuilding"
        git push
