name: test_main_result
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.3.0
        with:
          gradle-version: 6.1.1
      - name: Gradle Test
        run: gradle test --stacktrace
